---
# tasks file for server_create
- name: Waiting for Connection to Server...
  wait_for:
    port: 22
    host: "{{ ansible_main_host }}"
    timeout: 1000

- name: Trying Ping...
  ping:

- name: Test...
  debug: 
    msg: "IP Adress Server is {{ hostvars['local']['ip_main_server'] }}"

- name: Updating sources.list...
  apt:
    update_cache: yes

- name: Installing latest haproxy...
  package:
    name: "haproxy"
    state: latest

- name: Installing latest Keepalived...
  package:
    name: "keepalived"
    state: latest

- name: Configuring haproxy...
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg

- name: Restarting haproxy...
  command: sudo systemctl restart haproxy
